### PR TITLE
Add install.vbs and update readme file

### PR DESCRIPTION
**Pull request by kchitalia**
@wmathurin

### CODE REVIEW

**Comment by wmathurin** [comment]
Windows is so verbose ;-)

That looks fine. Where you able to run the app in Android studio on Windows?

**Comment by kchitalia** [comment]
I am seeing this error: 
Error:error reading C:\repo\SmartSyncExplorerReactNative\external\android\libs\SmartStore\libs\sqlcipher.jar; error in opening zip file
href="syncProject">Re-download dependencies and sync project (requires network)</a>
<a href="syncProject">Re-download dependencies and sync project (requires network)</a>

But that could just be something wrong on my end. Does not look like this has anything to do with the code itself.

**Comment by wmathurin** [comment]
We need to run the install.vbs in the android repo clone.
So the script should have something like that:

cd app/android
./install.vbs
cd ../..

(windows - style)

**Comment by kchitalia** [comment]
We need to add something similar in install.sh too, right?

**Comment by wmathurin** [comment]
We could but it's not needed.
iOS and Android's install.sh only initialize the submodules in their respective repo and we are already doing that here.
Android's install.vbs initiliazes the submodules AND  takes care of links (materializes them).

**Comment by kchitalia** [comment]
@wmathurin Added a section to run install.vbs for Android clone.

**Comment by wmathurin** [comment]
Can you build/run the app on Windows now?

**Comment by kchitalia** [comment]
Yep, I was able to build and run the app in an emulator.

**Comment by wmathurin** [comment]
Awesome. Then we are done.

**Pull request merged**
