### PR TITLE
More concise test

### PR DESCRIPTION
**Pull request by wmathurin**

### CODE REVIEW

**Comment by bhariharan** [comment]
:+1:

**Comment by kchitalia** [comment]
:+1:

**Comment by bhariharan** [comment]
Actually, is it possible that `currentUser != nil`, but `accessToken == nil` (in `temporaryUser` case)?

**Comment by wmathurin** [comment]
That's true. So I will close this pull request and change the tests in the various AppDelegate we have in the main repo.

**Pull request closed without merging**
